
-- PostgreSQL/Neon bootstrap schema for EarthVoice.
-- Run once against a new or existing Neon database before starting with the
-- production profile. The statements are idempotent where PostgreSQL allows it.

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    role VARCHAR(255),
    created_at TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS post (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content VARCHAR(10000) NOT NULL,
    category VARCHAR(80),
    created_at TIMESTAMP(6),
    image_url VARCHAR(1000),
    image_data BYTEA,
    image_content_type VARCHAR(100),
    author_id BIGINT REFERENCES users(id),
    like_count INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS comment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP(6),
    post_id BIGINT REFERENCES post(id),
    user_id BIGINT REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS contact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    message VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    message VARCHAR(2000) NOT NULL,
    type VARCHAR(80) NOT NULL,
    username VARCHAR(255),
    user_email VARCHAR(320),
    related_entity_id BIGINT,
    related_entity_type VARCHAR(80),
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS post_likes (
    post_id BIGINT NOT NULL REFERENCES post(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (post_id, user_id)
);

CREATE TABLE IF NOT EXISTS post_bookmarks (
    post_id BIGINT NOT NULL REFERENCES post(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (post_id, user_id)
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS name VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6);

-- Keep exactly one administrator: the designated account, when it exists.
UPDATE users
SET role = 'POSTER'
WHERE UPPER(COALESCE(role, '')) = 'ADMIN'
    AND LOWER(email) <> LOWER('elangovandev27@gmail.com');

UPDATE users
SET role = 'POSTER'
WHERE LOWER(email) = LOWER('elangovandev27@gmail.com')
    AND id <> (
            SELECT MIN(id)
            FROM users
            WHERE LOWER(email) = LOWER('elangovandev27@gmail.com')
    );

UPDATE users
SET name = 'Elangovan', role = 'ADMIN'
WHERE id = (
        SELECT MIN(id)
        FROM users
        WHERE LOWER(email) = LOWER('elangovandev27@gmail.com')
);

CREATE INDEX IF NOT EXISTS idx_notification_created_at
    ON notification (created_at);

CREATE INDEX IF NOT EXISTS idx_notification_is_read_created_at
    ON notification (is_read, created_at);
